sudo: required
language: generic
os: linux
services:
  - docker

before_install:
  - docker build -t phanumax/lab-k8s -f Dockerfile.dev .
  - docker run -d -p 8080:8080 --name kubia-http phanumax/kubia

script:
  - docker ps | grep -q kubia 