language: generic

services:
  - docker

before_install:
  - docker build -t phanumax/lab-k8s -f Dockerfile.dev .
  - docker run -d -p 8080:8080 --name kubia-http phanumax/kubia

script:
  - docker ps | grep -q kubia

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-330415815932"
  bucket_path: "docker-kubia"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key

